d04 = input('Digite algo: ')
print(type(d04))
print('Só tem espaços?', d04.isspace())
print('É um número?', d04.isnumeric())
print('É alfabético', d04.isalpha())
print('É alfanumérico', d04.isalnum())
print('Esta em maiúsculo', d04.isupper())
print('Esta em minúsculo', d04.islower())
print('Esta capitalizada', d04.istitle())